refasmer.exe -v -c -p -O "." "$env:STEAM_DIR\steamapps\common\Stardew Valley\MonoGame.Framework.dll"
refasmer.exe -v -c -p -O "." "$env:STEAM_DIR\steamapps\common\Stardew Valley\Stardew Valley.dll"
refasmer.exe -v -c -p -O "." "$env:STEAM_DIR\steamapps\common\Stardew Valley\StardewModdingAPI.dll"
refasmer.exe -v -c -p -O "." "$env:STEAM_DIR\steamapps\common\Stardew Valley\StardewValley.GameData.dll"
refasmer.exe -v -c -p -O "." "$env:STEAM_DIR\steamapps\common\Stardew Valley\xTile.dll"
refasmer.exe -v -c -p -O ".\smapi-internal" "$env:STEAM_DIR\steamapps\common\Stardew Valley\smapi-internal\SMAPI.Toolkit.CoreInterfaces.dll"
Copy-Item "$env:STEAM_DIR\steamapps\common\Stardew Valley\smapi-internal\SMAPI.Toolkit.CoreInterfaces.xml" -Destination ".\smapi-internal"
