name: Release
run-name: "Release Tag: ${{ github.ref_name }}"

on:
  push:
    tags:
      - '*/*.*.*'

jobs:
  create-releae:
    name: Build and created tagged release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Split tag
        uses: jungwinter/split@v2.1.0
        id: split
        with:
          msg: ${{ github.ref_name }}
          separator: '/'

      - name: Test split
        run: |
          echo ${{ steps.split.outputs._0 }}
          echo ${{ steps.split.outputs._1 }}

      - name: Checkout source code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.events.repository.default_branch }}

      - name: Setup dotnet 9.0.x
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '9.0.x'

      - name: Install dependencies
        run: dotnet restore ${{ steps.split.outputs._0 }}
        working-directory: src

      - name: Build
        run: dotnet build --force ${{ steps.split.outputs._0 }} -c Release -p:BuildConfig=GITHUB
        working-directory: src

      - name: Rename build zip
        shell: pwsh
        run: |
          mv "src/_releases/${{ steps.split.outputs._0 }} ${{ steps.split.outputs._1 }}.zip" "src/_releases/${{ steps.split.outputs._0 }}-${{ steps.split.outputs._1 }}.zip"

      - name: Generate attestations
        uses: actions/attest-build-provenance@v2
        id: attestation-step
        with:
          subject-path: |
            src/_releases/${{ steps.split.outputs._0 }}-${{ steps.split.outputs._1 }}.zip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'src/_releases/${{ steps.split.outputs._0 }}-${{ steps.split.outputs._1 }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.split.outputs._1 }}+${{ steps.split.outputs._0 }}
          name: '${{ steps.split.outputs._0 }} @ v${{ steps.split.outputs._1 }}'
          body: |
            Provenance Attestation: [View Attestation](${{ steps.attestation-step.outputs.attestation-url }})

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
