name: Release
run-name: "Release Tag: ${{ github.ref_name }}"

on:
  push:
    tags:
      - '*/v*.*.*'

jobs:
  create-releae:
    name: Build and created tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Split tag
        uses: jungwinter/split@v2.1.0
        id: split
        with:
          msg: ${{ github.ref_name }}
          separator: '/'

      # - name: Test split
      #   run: |
      #     echo ${{ steps.split.outputs._0 }}
      #     echo ${{ steps.split.outputs._1 }}

      - name: Checkout source code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.events.repository.default_branch }}

      - name: Setup dotnet 6.0.x
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore ${{ steps.split.outputs._0 }}
        working-directory: src

      - name: Build
        run: dotnet build ${{ steps.split.outputs._0 }} -c Release -p:EnableModDeploy=false -p:GamePath='/ref'
        working-directory: src
